[package]
name = "asdf_tool"
version = "0.0.1"
edition = "2021"

[dependencies]
extism-pdk = { workspace = true }
proto_pdk = { workspace = true }
schematic = { workspace = true }
serde = { workspace = true }

[lib]
crate-type = ['cdylib']

[features]
default = ["wasm"]
wasm = []
