use crate::config::RubyToolchainConfig;
use crate::gemfile;
use extism_pdk::*;
use moon_config::{DependencyScope, VersionSpec};
use moon_pdk::{locate_root_many, parse_toolchain_config_schema, plugin_err};
use moon_pdk_api::*;
use rubund::parser::{SourceType, parse_lockfile};
use starbase_utils::fs;
use std::collections::HashMap;
use std::path::{Component, Path, PathBuf};

// Files that mark a Bundler dependency root, lockfiles first (most precise),
// then manifests. Includes Bundler's alternative `gems.rb`/`gems.locked` names.
const ROOT_FILES: [&str; 4] = ["Gemfile.lock", "gems.locked", "Gemfile", "gems.rb"];
const DEFAULT_NON_PRODUCTION_GROUPS: [&str; 2] = ["development", "test"];

#[plugin_fn]
pub fn locate_dependencies_root(
    Json(input): Json<LocateDependenciesRootInput>,
) -> FnResult<Json<LocateDependenciesRootOutput>> {
    let mut output = LocateDependenciesRootOutput::default();

    // Bundler has no workspace concept (unlike npm/uv/Cargo), so each project
    // is its own dependency root and there are no members to report. Walk
    // upward for the nearest Gemfile/Gemfile.lock. If none is found, `root`
    // stays `None` and moon skips install steps for this project.
    if let Some(root) = locate_root_many(&input.starting_dir, &ROOT_FILES) {
        output.root = root.virtual_path();
    }

    Ok(Json(output))
}

#[plugin_fn]
pub fn setup_environment(
    Json(input): Json<SetupEnvironmentInput>,
) -> FnResult<Json<SetupEnvironmentOutput>> {
    let config = parse_toolchain_config_schema::<RubyToolchainConfig>(input.toolchain_config)?;
    let mut output = SetupEnvironmentOutput::default();

    // If Bundler is already configured for this root, skip the overhead.
    if input.root.join(".bundle/config").exists() {
        return Ok(Json(output));
    }

    // Install gems into a project-local directory (the Ruby analog of a venv /
    // node_modules) so installs are isolated, cacheable, and don't pollute a
    // shared Ruby. Persisted via `bundle config` rather than the deprecated
    // `bundle install --path` flag.
    let mut path_cmd = ExecCommandInput::new(
        "bundler",
        [
            "config",
            "set",
            "--local",
            "path",
            config.bundle_path.as_str(),
        ],
    );
    path_cmd.cwd = Some(input.root.clone());
    output.commands.push(path_cmd.into());

    // Frozen/deployment mode for reproducible installs: Bundler refuses to
    // mutate Gemfile.lock and errors if it's out of sync with the Gemfile.
    if config.frozen {
        let mut frozen_cmd =
            ExecCommandInput::new("bundler", ["config", "set", "--local", "frozen", "true"]);
        frozen_cmd.cwd = Some(input.root.clone());
        output.commands.push(frozen_cmd.into());
    }

    Ok(Json(output))
}

#[plugin_fn]
pub fn install_dependencies(
    Json(input): Json<InstallDependenciesInput>,
) -> FnResult<Json<InstallDependenciesOutput>> {
    let config = parse_toolchain_config_schema::<RubyToolchainConfig>(input.toolchain_config)?;
    let mut output = InstallDependenciesOutput::default();

    let mut command = ExecCommandInput::new("bundler", ["install"]);
    command.args.extend(config.bundler_install_args);
    command.cwd = Some(input.root.clone());

    // Production installs exclude dev/test groups. We use `BUNDLE_WITHOUT`
    // (colon-separated) rather than the `--without` flag, which is removed in
    // modern Bundler.
    if input.production {
        let groups = if config.production_without_groups.is_empty() {
            vec!["development".to_string(), "test".to_string()]
        } else {
            config.production_without_groups
        };

        command
            .env
            .insert("BUNDLE_WITHOUT".into(), groups.join(":"));
    }

    // Bundler's resolver already produces a single flat gem set, so there is
    // no separate dedupe step (unlike npm/yarn).
    output.install_command = Some(command.into());

    Ok(Json(output))
}

#[plugin_fn]
pub fn extend_command(
    Json(input): Json<ExtendCommandInput>,
) -> FnResult<Json<ExtendCommandOutput>> {
    let mut output = ExtendTaskCommandOutput::default();

    // Put a project's binstubs dir (`bin/`, generated by `bundle binstubs`) on
    // PATH so tasks can invoke e.g. `rspec` directly. `bundle exec <cmd>` works
    // regardless, via the `bundle` binary provided by the toolchain (tier 3).
    if let Some(root) = locate_root_many(&input.current_dir, &ROOT_FILES)
        && let Some(real) = root.real_path()
    {
        output.paths.push(real.join("bin"));
    }

    Ok(Json(output))
}

#[plugin_fn]
pub fn parse_lock(Json(input): Json<ParseLockInput>) -> FnResult<Json<ParseLockOutput>> {
    let mut output = ParseLockOutput::default();
    let content = fs::read_file(&input.path)?;
    let lock = parse_lockfile(&content);

    if !content.trim().is_empty()
        && lock.sources.is_empty()
        && lock.specs.is_empty()
        && lock.dependencies.is_empty()
    {
        return Err(plugin_err!(
            "could not parse Gemfile.lock: no recognizable sections found"
        ));
    }

    for spec in lock.specs {
        let (version, platform) = split_platform(spec.version);
        let mut dep = LockDependency {
            version: VersionSpec::parse(version).ok(),
            ..Default::default()
        };

        // Stash provenance in `meta`: platform, then git revision, then path.
        if let Some(platform) = platform {
            dep.meta = Some(platform.to_string());
        } else if let Some(source) = lock.sources.get(spec.source_index) {
            match source.type_ {
                SourceType::Git => dep.meta = source.revision.map(str::to_owned),
                SourceType::Path => {
                    let path = source.path.unwrap_or(source.remote);

                    if !path.is_empty() {
                        dep.meta = Some(format!("path:{path}"));
                    }
                }
                SourceType::Gem => {}
            }
        }

        if let Some((_, _, sha)) = lock.checksums.iter().find(|(name, checksum_version, _)| {
            *name == spec.name && *checksum_version == spec.version
        }) {
            dep.hash = Some((*sha).to_string());
        }

        output
            .dependencies
            .entry(spec.name.to_string())
            .or_default()
            .push(dep);
    }

    Ok(Json(output))
}

/// Split a lockfile version token into (version, platform). Gem versions never
/// contain `-`; in a spec line a trailing `-<platform>` denotes a native gem.
fn split_platform(raw: &str) -> (&str, Option<&str>) {
    match raw.split_once('-') {
        Some((version, platform)) => (version, Some(platform)),
        None => (raw, None),
    }
}

#[plugin_fn]
pub fn parse_manifest(
    Json(input): Json<ParseManifestInput>,
) -> FnResult<Json<ParseManifestOutput>> {
    let mut output = ParseManifestOutput::default();

    if matches!(
        input.path.file_name().and_then(|name| name.to_str()),
        Some("Gemfile" | "gems.rb")
    ) {
        let content = fs::read_file(&input.path)?;

        for gem in gemfile::parse_path_gems(&content) {
            insert_path_manifest_dep(&mut output, gem);
        }
    }

    Ok(Json(output))
}

fn insert_path_manifest_dep(output: &mut ParseManifestOutput, gem: gemfile::PathGem) {
    let dep = ManifestDependency::path(PathBuf::from(gem.path));

    match groups_to_scope(&gem.groups, &DEFAULT_NON_PRODUCTION_GROUPS) {
        DependencyScope::Development => output.dev_dependencies.insert(gem.name, dep),
        _ => output.dependencies.insert(gem.name, dep),
    };
}

#[plugin_fn]
pub fn extend_project_graph(
    Json(input): Json<ExtendProjectGraphInput>,
) -> FnResult<Json<ExtendProjectGraphOutput>> {
    let config = parse_toolchain_config_schema::<RubyToolchainConfig>(
        if input.toolchain_config.is_null() {
            serde_json::json!({})
        } else {
            input.toolchain_config.clone()
        },
    )?;
    let non_production_groups = non_production_groups(&config);
    let mut output = ExtendProjectGraphOutput::default();

    // Map each project's source directory to its id, so we can resolve a
    // `path:` gem reference back to the project it points at.
    let mut by_source: HashMap<PathBuf, Id> = HashMap::new();
    for (id, source) in &input.project_sources {
        by_source.insert(PathBuf::from(source), id.clone());
    }

    for (id, source) in &input.project_sources {
        let gemfile_path = input
            .context
            .get_project_root_from_source(source)
            .join("Gemfile");

        if !gemfile_path.exists() {
            continue;
        }

        let Ok(content) = fs::read_file(&gemfile_path) else {
            continue;
        };

        let mut project_output = ExtendProjectOutput::default();

        // Internal project relationships are expressed via `path:` gems, since
        // Bundler has no workspace concept.
        for gem in gemfile::parse_path_gems(&content) {
            // The join still needs normalizing to fold the `../..` in the
            // gem's relative path down to a workspace-relative source.
            let resolved = normalize(&Path::new(source).join(&gem.path));

            if let Some(dep_id) = by_source.get(&resolved)
                && dep_id != id
            {
                project_output.dependencies.push(ProjectDependency {
                    id: dep_id.clone(),
                    scope: groups_to_scope(&gem.groups, &non_production_groups),
                    via: Some(format!("path gem {}", gem.name)),
                });
            }
        }

        if !project_output.dependencies.is_empty() {
            output.extended_projects.insert(id.clone(), project_output);
        }

        if let Some(file) = gemfile_path.virtual_path() {
            output.input_files.push(file);
        }
    }

    Ok(Json(output))
}

fn non_production_groups(config: &RubyToolchainConfig) -> Vec<&str> {
    if config.production_without_groups.is_empty() {
        DEFAULT_NON_PRODUCTION_GROUPS.to_vec()
    } else {
        config
            .production_without_groups
            .iter()
            .map(String::as_str)
            .collect()
    }
}

fn groups_to_scope(groups: &[String], non_production_groups: &[&str]) -> DependencyScope {
    if groups
        .iter()
        .any(|group| non_production_groups.contains(&group.as_str()))
    {
        DependencyScope::Development
    } else {
        DependencyScope::Production
    }
}

#[plugin_fn]
pub fn hash_task_contents(
    Json(input): Json<HashTaskContentsInput>,
) -> FnResult<Json<HashTaskContentsOutput>> {
    let config = parse_toolchain_config_schema::<RubyToolchainConfig>(input.toolchain_config)?;

    // Fold toolchain state that isn't already a hashed input file (the resolved
    // Ruby version and install settings) into the task's cache key, so caches
    // don't collide across Ruby versions / configs.
    let contents = vec![serde_json::json!({
        "version": config.version.map(|v| v.to_string()),
        "bundlePath": config.bundle_path,
        "frozen": config.frozen,
    })];

    Ok(Json(HashTaskContentsOutput { contents }))
}

/// Resolve `.`/`..` components in a relative path without touching the
/// filesystem, so `apps/web` + `../../libs/billing` -> `libs/billing`.
fn normalize(path: &Path) -> PathBuf {
    let mut out = PathBuf::new();

    for comp in path.components() {
        match comp {
            Component::ParentDir => {
                out.pop();
            }
            Component::CurDir => {}
            other => out.push(other.as_os_str()),
        }
    }

    out
}
