use crate::config::RubyToolchainConfig;
use crate::gemfile::{self, Scope};
use crate::gemfile_lock::{self, SourceType};
use extism_pdk::*;
use moon_config::{DependencyScope, UnresolvedVersionSpec, Version, VersionSpec};
use moon_pdk::{locate_root_many, parse_toolchain_config_schema};
use moon_pdk_api::*;
use starbase_utils::fs;
use std::collections::HashMap;
use std::path::{Component, Path, PathBuf};

// Files that mark a Bundler dependency root, lockfiles first (most precise),
// then manifests. Includes Bundler's alternative `gems.rb`/`gems.locked` names.
const ROOT_FILES: [&str; 4] = ["Gemfile.lock", "gems.locked", "Gemfile", "gems.rb"];

#[plugin_fn]
pub fn locate_dependencies_root(
    Json(input): Json<LocateDependenciesRootInput>,
) -> FnResult<Json<LocateDependenciesRootOutput>> {
    let mut output = LocateDependenciesRootOutput::default();

    // Bundler has no workspace concept (unlike npm/uv/Cargo), so each project
    // is its own dependency root and there are no members to report. Walk
    // upward for the nearest Gemfile/Gemfile.lock. If none is found, `root`
    // stays `None` and moon skips install steps for this project.
    if let Some(root) = locate_root_many(&input.starting_dir, &ROOT_FILES) {
        output.root = root.virtual_path();
    }

    Ok(Json(output))
}

#[plugin_fn]
pub fn setup_environment(
    Json(input): Json<SetupEnvironmentInput>,
) -> FnResult<Json<SetupEnvironmentOutput>> {
    let config = parse_toolchain_config_schema::<RubyToolchainConfig>(input.toolchain_config)?;
    let mut output = SetupEnvironmentOutput::default();

    // If Bundler is already configured for this root, skip the overhead.
    if input.root.join(".bundle/config").exists() {
        return Ok(Json(output));
    }

    // Install gems into a project-local directory (the Ruby analog of a venv /
    // node_modules) so installs are isolated, cacheable, and don't pollute a
    // shared Ruby. Persisted via `bundle config` rather than the deprecated
    // `bundle install --path` flag.
    let mut path_cmd = ExecCommandInput::new(
        "bundle",
        [
            "config",
            "set",
            "--local",
            "path",
            config.bundle_path.as_str(),
        ],
    );
    path_cmd.cwd = Some(input.root.clone());
    output.commands.push(path_cmd.into());

    // Frozen/deployment mode for reproducible installs: Bundler refuses to
    // mutate Gemfile.lock and errors if it's out of sync with the Gemfile.
    if config.frozen {
        let mut frozen_cmd =
            ExecCommandInput::new("bundle", ["config", "set", "--local", "frozen", "true"]);
        frozen_cmd.cwd = Some(input.root.clone());
        output.commands.push(frozen_cmd.into());
    }

    Ok(Json(output))
}

#[plugin_fn]
pub fn install_dependencies(
    Json(input): Json<InstallDependenciesInput>,
) -> FnResult<Json<InstallDependenciesOutput>> {
    let config = parse_toolchain_config_schema::<RubyToolchainConfig>(input.toolchain_config)?;
    let mut output = InstallDependenciesOutput::default();

    let mut command = ExecCommandInput::new("bundle", ["install"]);
    command.args.extend(config.bundler_install_args);
    command.cwd = Some(input.root.clone());

    // Production installs exclude dev/test groups. We use `BUNDLE_WITHOUT`
    // (colon-separated) rather than the `--without` flag, which is removed in
    // modern Bundler.
    if input.production {
        let groups = if config.production_without_groups.is_empty() {
            vec!["development".to_string(), "test".to_string()]
        } else {
            config.production_without_groups
        };

        command
            .env
            .insert("BUNDLE_WITHOUT".into(), groups.join(":"));
    }

    // Bundler's resolver already produces a single flat gem set, so there is
    // no separate dedupe step (unlike npm/yarn).
    output.install_command = Some(command.into());

    Ok(Json(output))
}

#[plugin_fn]
pub fn extend_command(
    Json(input): Json<ExtendCommandInput>,
) -> FnResult<Json<ExtendCommandOutput>> {
    let mut output = ExtendTaskCommandOutput::default();

    // Put a project's binstubs dir (`bin/`, generated by `bundle binstubs`) on
    // PATH so tasks can invoke e.g. `rspec` directly. `bundle exec <cmd>` works
    // regardless, via the `bundle` binary provided by the toolchain (tier 3).
    if let Some(root) = locate_root_many(&input.current_dir, &ROOT_FILES)
        && let Some(real) = root.real_path()
    {
        output.paths.push(real.join("bin"));
    }

    Ok(Json(output))
}

#[plugin_fn]
pub fn parse_lock(Json(input): Json<ParseLockInput>) -> FnResult<Json<ParseLockOutput>> {
    let mut output = ParseLockOutput::default();
    let content = fs::read_file(&input.path)?;
    let lock = gemfile_lock::parse(&content)?;

    for spec in lock.specs {
        let mut dep = LockDependency {
            version: VersionSpec::parse(&spec.version).ok(),
            ..Default::default()
        };

        // Stash provenance in `meta`: platform, then git revision, then path.
        if let Some(platform) = &spec.platform {
            dep.meta = Some(platform.clone());
        } else if let Some(source) = lock.sources.get(spec.source_index) {
            match source.type_ {
                SourceType::Git => dep.meta = source.revision.clone(),
                SourceType::Path => dep.meta = Some(format!("path:{}", source.remote)),
                SourceType::Gem => {}
            }
        }

        if let Some(sha) = lock
            .checksums
            .get(&format!("{} {}", spec.name, spec.version))
        {
            dep.hash = Some(sha.clone());
        }

        output.dependencies.entry(spec.name).or_default().push(dep);
    }

    Ok(Json(output))
}

#[plugin_fn]
pub fn parse_manifest(
    Json(input): Json<ParseManifestInput>,
) -> FnResult<Json<ParseManifestOutput>> {
    let mut output = ParseManifestOutput::default();
    let content = fs::read_file(&input.path)?;

    match input.path.file_name().and_then(|name| name.to_str()) {
        Some("Gemfile") | Some("gems.rb") => {
            for decl in gemfile::parse_gemfile(&content) {
                insert_manifest_dep(&mut output, decl);
            }
        }
        Some(name) if name.ends_with(".gemspec") => {
            let spec = gemfile::parse_gemspec(&content);

            if let Some(version) = &spec.version {
                output.version = Version::parse(version).ok();
            }

            for decl in spec.dependencies {
                insert_manifest_dep(&mut output, decl);
            }
        }
        _ => {}
    };

    Ok(Json(output))
}

fn insert_manifest_dep(output: &mut ParseManifestOutput, decl: gemfile::GemDecl) {
    let mut config = ManifestDependencyConfig::default();

    if let Some(path) = &decl.path {
        config.path = Some(PathBuf::from(path));
    }
    if let Some(git) = &decl.git {
        config.url = Some(git.clone());
    }
    if let Some(req) = &decl.requirement {
        // Ruby's `~>` and friends often don't map to moon's spec syntax; keep
        // it when parseable, otherwise the lockfile remains the source of truth.
        config.version = UnresolvedVersionSpec::parse(req).ok();
    }

    let dep = ManifestDependency::Config(config);

    match decl.scope {
        Scope::Runtime => output.dependencies.insert(decl.name, dep),
        Scope::Development => output.dev_dependencies.insert(decl.name, dep),
    };
}

#[plugin_fn]
pub fn extend_project_graph(
    Json(input): Json<ExtendProjectGraphInput>,
) -> FnResult<Json<ExtendProjectGraphOutput>> {
    let mut output = ExtendProjectGraphOutput::default();

    // Map each project's source directory to its id, so we can resolve a
    // `path:` gem reference back to the project it points at.
    let mut by_source: HashMap<PathBuf, Id> = HashMap::new();
    for (id, source) in &input.project_sources {
        by_source.insert(PathBuf::from(source), id.clone());
    }

    for (id, source) in &input.project_sources {
        let gemfile_path = input
            .context
            .get_project_root_from_source(source)
            .join("Gemfile");

        if !gemfile_path.exists() {
            continue;
        }

        let Ok(content) = fs::read_file(&gemfile_path) else {
            continue;
        };

        let mut project_output = ExtendProjectOutput::default();

        // Internal project relationships are expressed via `path:` gems, since
        // Bundler has no workspace concept.
        for decl in gemfile::parse_gemfile(&content) {
            let Some(path) = &decl.path else {
                continue;
            };

            // The join still needs normalizing to fold the `../..` in the
            // gem's relative path down to a workspace-relative source.
            let resolved = normalize(&Path::new(source).join(path));

            if let Some(dep_id) = by_source.get(&resolved)
                && dep_id != id
            {
                project_output.dependencies.push(ProjectDependency {
                    id: dep_id.clone(),
                    scope: match decl.scope {
                        Scope::Development => DependencyScope::Development,
                        Scope::Runtime => DependencyScope::Production,
                    },
                    via: Some(format!("path gem {}", decl.name)),
                });
            }
        }

        if !project_output.dependencies.is_empty() {
            output.extended_projects.insert(id.clone(), project_output);
        }

        if let Some(file) = gemfile_path.virtual_path() {
            output.input_files.push(file);
        }
    }

    Ok(Json(output))
}

#[plugin_fn]
pub fn hash_task_contents(
    Json(input): Json<HashTaskContentsInput>,
) -> FnResult<Json<HashTaskContentsOutput>> {
    let config = parse_toolchain_config_schema::<RubyToolchainConfig>(input.toolchain_config)?;

    // Fold toolchain state that isn't already a hashed input file (the resolved
    // Ruby version and install settings) into the task's cache key, so caches
    // don't collide across Ruby versions / configs.
    let contents = vec![serde_json::json!({
        "version": config.version.map(|v| v.to_string()),
        "bundlePath": config.bundle_path,
        "frozen": config.frozen,
    })];

    Ok(Json(HashTaskContentsOutput { contents }))
}

/// Resolve `.`/`..` components in a relative path without touching the
/// filesystem, so `apps/web` + `../../libs/billing` -> `libs/billing`.
fn normalize(path: &Path) -> PathBuf {
    let mut out = PathBuf::new();

    for comp in path.components() {
        match comp {
            Component::ParentDir => {
                out.pop();
            }
            Component::CurDir => {}
            other => out.push(other.as_os_str()),
        }
    }

    out
}
