$schema: "./cache/schemas/workspace.json"

projects:
  root: .
  # Backends
  asdf-backend: backends/asdf
  # Common
  extension-common: crates/extension-common
  lang-javascript-common: crates/lang-javascript-common
  # Extensions
  download-extension: extensions/download
  migrate-nx-extension: extensions/migrate-nx
  migrate-turborepo-extension: extensions/migrate-turborepo
  unpack-extension: extensions/unpack
  # Tools
  bun-tool: tools/bun
  deno-tool: tools/deno
  go-tool: tools/go
  moon-tool: tools/moon
  node-tool: tools/node
  node-depman-tool: tools/node-depman
  proto-tool: tools/proto
  python-tool: tools/python
  python-poetry-tool: tools/python-poetry
  python-uv-tool: tools/python-uv
  ruby-tool: tools/ruby
  rust-tool: tools/rust
  schema-tool: tools/internal-schema
  # Toolchains
  go-toolchain: toolchains/go
  node-toolchain: toolchains/node
  rust-toolchain: toolchains/rust
  typescript-toolchain: toolchains/typescript

pipeline:
  logRunningCommand: true

unstable_remote:
  host: "grpcs://cache.depot.dev"
  auth:
    token: "DEPOT_TOKEN"
    headers:
      "X-Depot-Org": "1xtpjd084j"
      "X-Depot-Project": "n30s525s5q"
